package com.matsupy.cmn.entity;

public class UserTbl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_tbl.id
     *
     * @mbg.generated Sun Oct 26 13:18:12 JST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_tbl.name
     *
     * @mbg.generated Sun Oct 26 13:18:12 JST 2025
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_tbl.id
     *
     * @return the value of public.user_tbl.id
     *
     * @mbg.generated Sun Oct 26 13:18:12 JST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_tbl.id
     *
     * @param id the value for public.user_tbl.id
     *
     * @mbg.generated Sun Oct 26 13:18:12 JST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_tbl.name
     *
     * @return the value of public.user_tbl.name
     *
     * @mbg.generated Sun Oct 26 13:18:12 JST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_tbl.name
     *
     * @param name the value for public.user_tbl.name
     *
     * @mbg.generated Sun Oct 26 13:18:12 JST 2025
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}