package com.matsupy.cmn.mapper;

import com.matsupy.cmn.entity.UserTbl;

public interface UserTblMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_tbl
     *
     * @mbg.generated Sun Oct 26 13:18:12 JST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_tbl
     *
     * @mbg.generated Sun Oct 26 13:18:12 JST 2025
     */
    int insert(UserTbl row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_tbl
     *
     * @mbg.generated Sun Oct 26 13:18:12 JST 2025
     */
    int insertSelective(UserTbl row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_tbl
     *
     * @mbg.generated Sun Oct 26 13:18:12 JST 2025
     */
    UserTbl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_tbl
     *
     * @mbg.generated Sun Oct 26 13:18:12 JST 2025
     */
    int updateByPrimaryKeySelective(UserTbl row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_tbl
     *
     * @mbg.generated Sun Oct 26 13:18:12 JST 2025
     */
    int updateByPrimaryKey(UserTbl row);
}